### ISSUE TITLE
Is the ERFA or SOFA method correct?

### ISSUE THREAD

**Issue by cxwx** [d33psky/J2000-JNow#4]
result from library erfa and sofa is quite different.
Is the method correct?

**Comment by d33psky** [comment]
Hi cxwx,
Good question, It's the reason I started this project; to answer that very question !
Have a look at the code, especially comparelibNOVA-NOVAS-SOFA-ERFA.c , it's less than 250 lines of code and should be easy to read. It's what calls the various libraries and compares their results against each other.
I put this up almost 3 years ago and have not received a single pull request or hint that brings the library results closer to each other yet.
-- Hans

**Comment by cxwx** [comment]
Hi:
   I've saw the code, but I'm sorry I'm not expert of astronomy. 
   I'm looking forwarding the answer of the same question too, so I found this repo.

**Comment by cxwx** [comment]
The method SOFA and ERFA should be modified.

**Comment by d33psky** [comment]
Both ? How ? Are you making a PR ?

**Comment by cxwx** [comment]
using the SOFA and ERFA, one need to set polar motion correctly.

**Comment by cxwx** [comment]
sorry for long time no answer.
I made a mistake. it was not polar motion difference.
The libnova use the IAU1976 while the lib sofa use the IAU2000 or IAU2013. That's the difference. (the axis system is not exactly the same)
and the sofa also support IAU1976 in its code
